IncomingMessage {
    _readableState: ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList {
            head: null,
            tail: null,
            length: 0
        },
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: null,
        ended: true,
        endEmitted: false,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: true,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: true,
        decoder: null,
        encoding: null
    },
    readable: true,
    _events: {},
    _eventsCount: 0,
    _maxListeners: undefined,
    socket: Socket {
        connecting: false,
        _hadError: false,
        _handle: TCP {
            reading: true,
            owner: [Circular],
            onread: [Function: onread],
            onconnection: null,
            _consumed: true
        },
        _parent: null,
        _host: null,
        _readableState: ReadableState {
            objectMode: false,
            highWaterMark: 16384,
            buffer: [BufferList],
            length: 0,
            pipes: null,
            pipesCount: 0,
            flowing: true,
            ended: false,
            endEmitted: false,
            reading: true,
            sync: false,
            needReadable: true,
            emittedReadable: false,
            readableListening: false,
            resumeScheduled: false,
            destroyed: false,
            defaultEncoding: 'utf8',
            awaitDrain: 0,
            readingMore: false,
            decoder: null,
            encoding: null
        },
        readable: true,
        _events: {
            finish: [Function: onSocketFinish],
            end: [Array],
            drain: [Array],
            timeout: [Function: socketOnTimeout],
            data: [Function: bound socketOnData],
            error: [Array],
            close: [Array],
            resume: [Function: onSocketResume],
            pause: [Function: onSocketPause]
        },
        _eventsCount: 9,
        _maxListeners: undefined,
        _writableState: WritableState {
            objectMode: false,
            highWaterMark: 16384,
            finalCalled: false,
            needDrain: false,
            ending: false,
            ended: false,
            finished: false,
            destroyed: false,
            decodeStrings: false,
            defaultEncoding: 'utf8',
            length: 0,
            writing: false,
            corked: 0,
            sync: true,
            bufferProcessing: false,
            onwrite: [Function: bound onwrite],
            writecb: null,
            writelen: 0,
            bufferedRequest: null,
            lastBufferedRequest: null,
            pendingcb: 0,
            prefinished: false,
            errorEmitted: false,
            bufferedRequestCount: 0,
            corkedRequestsFree: [Object]
        },
        writable: true,
        _bytesDispatched: 0,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        allowHalfOpen: true,
        server: Server {
            _events: [Object],
            _eventsCount: 4,
            _maxListeners: undefined,
            _connections: 1,
            _handle: [TCP],
            _usingWorkers: false,
            _workers: [],
            _unref: false,
            allowHalfOpen: true,
            pauseOnConnect: false,
            httpAllowHalfOpen: false,
            timeout: 120000,
            keepAliveTimeout: 5000,
            _pendingResponseData: 0,
            maxHeadersCount: null,
            _connectionKey: '6::::3000',
            [Symbol(IncomingMessage)]: [Function],
            [Symbol(ServerResponse)]: [Function],
            [Symbol(asyncId)]: 6
        },
        _server: Server {
            _events: [Object],
            _eventsCount: 4,
            _maxListeners: undefined,
            _connections: 1,
            _handle: [TCP],
            _usingWorkers: false,
            _workers: [],
            _unref: false,
            allowHalfOpen: true,
            pauseOnConnect: false,
            httpAllowHalfOpen: false,
            timeout: 120000,
            keepAliveTimeout: 5000,
            _pendingResponseData: 0,
            maxHeadersCount: null,
            _connectionKey: '6::::3000',
            [Symbol(IncomingMessage)]: [Function],
            [Symbol(ServerResponse)]: [Function],
            [Symbol(asyncId)]: 6
        },
        _idleTimeout: 120000,
        _idleNext: TimersList {
            _idleNext: [Circular],
            _idlePrev: [Circular],
            _unrefed: true,
            msecs: 120000,
            nextTick: false,
            _timer: [Timer]
        },
        _idlePrev: TimersList {
            _idleNext: [Circular],
            _idlePrev: [Circular],
            _unrefed: true,
            msecs: 120000,
            nextTick: false,
            _timer: [Timer]
        },
        _idleStart: 599,
        _destroyed: false,
        parser: HTTPParser {
            '0': [Function: parserOnHeaders],
            '1': [Function: parserOnHeadersComplete],
            '2': [Function: parserOnBody],
            '3': [Function: parserOnMessageComplete],
            '4': [Function: bound onParserExecute],
            _headers: [],
            _url: '',
            _consumed: true,
            socket: [Circular],
            incoming: [Circular],
            outgoing: null,
            maxHeaderPairs: 2000,
            onIncoming: [Function: bound parserOnIncoming]
        },
        on: [Function: socketOnWrap],
        _paused: false,
        _httpMessage: ServerResponse {
            _events: [Object],
            _eventsCount: 2,
            _maxListeners: undefined,
            output: [],
            outputEncodings: [],
            outputCallbacks: [],
            outputSize: 0,
            writable: true,
            _last: false,
            upgrading: false,
            chunkedEncoding: false,
            shouldKeepAlive: false,
            useChunkedEncodingByDefault: true,
            sendDate: true,
            _removedConnection: false,
            _removedContLen: false,
            _removedTE: false,
            _contentLength: null,
            _hasBody: true,
            _trailer: '',
            finished: false,
            _headerSent: false,
            socket: [Circular],
            connection: [Circular],
            _header: null,
            _onPendingData: [Function: bound updateOutgoingData],
            _sent100: false,
            _expect_continue: false,
            req: [Circular],
            locals: {},
            _startAt: undefined,
            _startTime: undefined,
            writeHead: [Function: writeHead],
            __onFinished: [Function],
            [Symbol(isCorked)]: false,
            [Symbol(outHeadersKey)]: [Object]
        },
        _peername: {
            address: '::1',
            family: 'IPv6',
            port: 50977
        },
        [Symbol(asyncId)]: 8,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(bytesRead)]: 0,
        [Symbol(asyncId)]: 10,
        [Symbol(triggerAsyncId)]: 8
    },
    connection: Socket {
        connecting: false,
        _hadError: false,
        _handle: TCP {
            reading: true,
            owner: [Circular],
            onread: [Function: onread],
            onconnection: null,
            _consumed: true
        },
        _parent: null,
        _host: null,
        _readableState: ReadableState {
            objectMode: false,
            highWaterMark: 16384,
            buffer: [BufferList],
            length: 0,
            pipes: null,
            pipesCount: 0,
            flowing: true,
            ended: false,
            endEmitted: false,
            reading: true,
            sync: false,
            needReadable: true,
            emittedReadable: false,
            readableListening: false,
            resumeScheduled: false,
            destroyed: false,
            defaultEncoding: 'utf8',
            awaitDrain: 0,
            readingMore: false,
            decoder: null,
            encoding: null
        },
        readable: true,
        _events: {
            finish: [Function: onSocketFinish],
            end: [Array],
            drain: [Array],
            timeout: [Function: socketOnTimeout],
            data: [Function: bound socketOnData],
            error: [Array],
            close: [Array],
            resume: [Function: onSocketResume],
            pause: [Function: onSocketPause]
        },
        _eventsCount: 9,
        _maxListeners: undefined,
        _writableState: WritableState {
            objectMode: false,
            highWaterMark: 16384,
            finalCalled: false,
            needDrain: false,
            ending: false,
            ended: false,
            finished: false,
            destroyed: false,
            decodeStrings: false,
            defaultEncoding: 'utf8',
            length: 0,
            writing: false,
            corked: 0,
            sync: true,
            bufferProcessing: false,
            onwrite: [Function: bound onwrite],
            writecb: null,
            writelen: 0,
            bufferedRequest: null,
            lastBufferedRequest: null,
            pendingcb: 0,
            prefinished: false,
            errorEmitted: false,
            bufferedRequestCount: 0,
            corkedRequestsFree: [Object]
        },
        writable: true,
        _bytesDispatched: 0,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        allowHalfOpen: true,
        server: Server {
            _events: [Object],
            _eventsCount: 4,
            _maxListeners: undefined,
            _connections: 1,
            _handle: [TCP],
            _usingWorkers: false,
            _workers: [],
            _unref: false,
            allowHalfOpen: true,
            pauseOnConnect: false,
            httpAllowHalfOpen: false,
            timeout: 120000,
            keepAliveTimeout: 5000,
            _pendingResponseData: 0,
            maxHeadersCount: null,
            _connectionKey: '6::::3000',
            [Symbol(IncomingMessage)]: [Function],
            [Symbol(ServerResponse)]: [Function],
            [Symbol(asyncId)]: 6
        },
        _server: Server {
            _events: [Object],
            _eventsCount: 4,
            _maxListeners: undefined,
            _connections: 1,
            _handle: [TCP],
            _usingWorkers: false,
            _workers: [],
            _unref: false,
            allowHalfOpen: true,
            pauseOnConnect: false,
            httpAllowHalfOpen: false,
            timeout: 120000,
            keepAliveTimeout: 5000,
            _pendingResponseData: 0,
            maxHeadersCount: null,
            _connectionKey: '6::::3000',
            [Symbol(IncomingMessage)]: [Function],
            [Symbol(ServerResponse)]: [Function],
            [Symbol(asyncId)]: 6
        },
        _idleTimeout: 120000,
        _idleNext: TimersList {
            _idleNext: [Circular],
            _idlePrev: [Circular],
            _unrefed: true,
            msecs: 120000,
            nextTick: false,
            _timer: [Timer]
        },
        _idlePrev: TimersList {
            _idleNext: [Circular],
            _idlePrev: [Circular],
            _unrefed: true,
            msecs: 120000,
            nextTick: false,
            _timer: [Timer]
        },
        _idleStart: 599,
        _destroyed: false,
        parser: HTTPParser {
            '0': [Function: parserOnHeaders],
            '1': [Function: parserOnHeadersComplete],
            '2': [Function: parserOnBody],
            '3': [Function: parserOnMessageComplete],
            '4': [Function: bound onParserExecute],
            _headers: [],
            _url: '',
            _consumed: true,
            socket: [Circular],
            incoming: [Circular],
            outgoing: null,
            maxHeaderPairs: 2000,
            onIncoming: [Function: bound parserOnIncoming]
        },
        on: [Function: socketOnWrap],
        _paused: false,
        _httpMessage: ServerResponse {
            _events: [Object],
            _eventsCount: 2,
            _maxListeners: undefined,
            output: [],
            outputEncodings: [],
            outputCallbacks: [],
            outputSize: 0,
            writable: true,
            _last: false,
            upgrading: false,
            chunkedEncoding: false,
            shouldKeepAlive: false,
            useChunkedEncodingByDefault: true,
            sendDate: true,
            _removedConnection: false,
            _removedContLen: false,
            _removedTE: false,
            _contentLength: null,
            _hasBody: true,
            _trailer: '',
            finished: false,
            _headerSent: false,
            socket: [Circular],
            connection: [Circular],
            _header: null,
            _onPendingData: [Function: bound updateOutgoingData],
            _sent100: false,
            _expect_continue: false,
            req: [Circular],
            locals: {},
            _startAt: undefined,
            _startTime: undefined,
            writeHead: [Function: writeHead],
            __onFinished: [Function],
            [Symbol(isCorked)]: false,
            [Symbol(outHeadersKey)]: [Object]
        },
        _peername: {
            address: '::1',
            family: 'IPv6',
            port: 50977
        },
        [Symbol(asyncId)]: 8,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(bytesRead)]: 0,
        [Symbol(asyncId)]: 10,
        [Symbol(triggerAsyncId)]: 8
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    headers: {
        'user-agent': 'ShareX',
        host: 'localhost:3000',
        connection: 'Close'
    },
    rawHeaders: ['User-Agent',
        'ShareX',
        'Host',
        'localhost:3000',
        'Connection',
        'Close'
    ],
    trailers: {},
    rawTrailers: [],
    upgrade: false,
    url: '/api/v1/shortener?url=https%3a%2f%2fgetsharex.com',
    method: 'GET',
    statusCode: null,
    statusMessage: null,
    client: Socket {
        connecting: false,
        _hadError: false,
        _handle: TCP {
            reading: true,
            owner: [Circular],
            onread: [Function: onread],
            onconnection: null,
            _consumed: true
        },
        _parent: null,
        _host: null,
        _readableState: ReadableState {
            objectMode: false,
            highWaterMark: 16384,
            buffer: [BufferList],
            length: 0,
            pipes: null,
            pipesCount: 0,
            flowing: true,
            ended: false,
            endEmitted: false,
            reading: true,
            sync: false,
            needReadable: true,
            emittedReadable: false,
            readableListening: false,
            resumeScheduled: false,
            destroyed: false,
            defaultEncoding: 'utf8',
            awaitDrain: 0,
            readingMore: false,
            decoder: null,
            encoding: null
        },
        readable: true,
        _events: {
            finish: [Function: onSocketFinish],
            end: [Array],
            drain: [Array],
            timeout: [Function: socketOnTimeout],
            data: [Function: bound socketOnData],
            error: [Array],
            close: [Array],
            resume: [Function: onSocketResume],
            pause: [Function: onSocketPause]
        },
        _eventsCount: 9,
        _maxListeners: undefined,
        _writableState: WritableState {
            objectMode: false,
            highWaterMark: 16384,
            finalCalled: false,
            needDrain: false,
            ending: false,
            ended: false,
            finished: false,
            destroyed: false,
            decodeStrings: false,
            defaultEncoding: 'utf8',
            length: 0,
            writing: false,
            corked: 0,
            sync: true,
            bufferProcessing: false,
            onwrite: [Function: bound onwrite],
            writecb: null,
            writelen: 0,
            bufferedRequest: null,
            lastBufferedRequest: null,
            pendingcb: 0,
            prefinished: false,
            errorEmitted: false,
            bufferedRequestCount: 0,
            corkedRequestsFree: [Object]
        },
        writable: true,
        _bytesDispatched: 0,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        allowHalfOpen: true,
        server: Server {
            _events: [Object],
            _eventsCount: 4,
            _maxListeners: undefined,
            _connections: 1,
            _handle: [TCP],
            _usingWorkers: false,
            _workers: [],
            _unref: false,
            allowHalfOpen: true,
            pauseOnConnect: false,
            httpAllowHalfOpen: false,
            timeout: 120000,
            keepAliveTimeout: 5000,
            _pendingResponseData: 0,
            maxHeadersCount: null,
            _connectionKey: '6::::3000',
            [Symbol(IncomingMessage)]: [Function],
            [Symbol(ServerResponse)]: [Function],
            [Symbol(asyncId)]: 6
        },
        _server: Server {
            _events: [Object],
            _eventsCount: 4,
            _maxListeners: undefined,
            _connections: 1,
            _handle: [TCP],
            _usingWorkers: false,
            _workers: [],
            _unref: false,
            allowHalfOpen: true,
            pauseOnConnect: false,
            httpAllowHalfOpen: false,
            timeout: 120000,
            keepAliveTimeout: 5000,
            _pendingResponseData: 0,
            maxHeadersCount: null,
            _connectionKey: '6::::3000',
            [Symbol(IncomingMessage)]: [Function],
            [Symbol(ServerResponse)]: [Function],
            [Symbol(asyncId)]: 6
        },
        _idleTimeout: 120000,
        _idleNext: TimersList {
            _idleNext: [Circular],
            _idlePrev: [Circular],
            _unrefed: true,
            msecs: 120000,
            nextTick: false,
            _timer: [Timer]
        },
        _idlePrev: TimersList {
            _idleNext: [Circular],
            _idlePrev: [Circular],
            _unrefed: true,
            msecs: 120000,
            nextTick: false,
            _timer: [Timer]
        },
        _idleStart: 599,
        _destroyed: false,
        parser: HTTPParser {
            '0': [Function: parserOnHeaders],
            '1': [Function: parserOnHeadersComplete],
            '2': [Function: parserOnBody],
            '3': [Function: parserOnMessageComplete],
            '4': [Function: bound onParserExecute],
            _headers: [],
            _url: '',
            _consumed: true,
            socket: [Circular],
            incoming: [Circular],
            outgoing: null,
            maxHeaderPairs: 2000,
            onIncoming: [Function: bound parserOnIncoming]
        },
        on: [Function: socketOnWrap],
        _paused: false,
        _httpMessage: ServerResponse {
            _events: [Object],
            _eventsCount: 2,
            _maxListeners: undefined,
            output: [],
            outputEncodings: [],
            outputCallbacks: [],
            outputSize: 0,
            writable: true,
            _last: false,
            upgrading: false,
            chunkedEncoding: false,
            shouldKeepAlive: false,
            useChunkedEncodingByDefault: true,
            sendDate: true,
            _removedConnection: false,
            _removedContLen: false,
            _removedTE: false,
            _contentLength: null,
            _hasBody: true,
            _trailer: '',
            finished: false,
            _headerSent: false,
            socket: [Circular],
            connection: [Circular],
            _header: null,
            _onPendingData: [Function: bound updateOutgoingData],
            _sent100: false,
            _expect_continue: false,
            req: [Circular],
            locals: {},
            _startAt: undefined,
            _startTime: undefined,
            writeHead: [Function: writeHead],
            __onFinished: [Function],
            [Symbol(isCorked)]: false,
            [Symbol(outHeadersKey)]: [Object]
        },
        _peername: {
            address: '::1',
            family: 'IPv6',
            port: 50977
        },
        [Symbol(asyncId)]: 8,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(bytesRead)]: 0,
        [Symbol(asyncId)]: 10,
        [Symbol(triggerAsyncId)]: 8
    },
    _consuming: false,
    _dumped: false,
    next: [Function: next],
    baseUrl: '',
    originalUrl: '/api/v1/shortener?url=https%3a%2f%2fgetsharex.com',
    _parsedUrl: Url {
        protocol: null,
        slashes: null,
        auth: null,
        host: null,
        port: null,
        hostname: null,
        hash: null,
        search: '?url=https%3a%2f%2fgetsharex.com',
        query: 'url=https%3a%2f%2fgetsharex.com',
        pathname: '/api/v1/shortener',
        path: '/api/v1/shortener?url=https%3a%2f%2fgetsharex.com',
        href: '/api/v1/shortener?url=https%3a%2f%2fgetsharex.com',
        _raw: '/api/v1/shortener?url=https%3a%2f%2fgetsharex.com'
    },
    params: {},
    query: {
        url: 'https://getsharex.com'
    },
    res: ServerResponse {
        _events: {
            finish: [Array],
            end: [Function: onevent]
        },
        _eventsCount: 2,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: false,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: true,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: false,
        _headerSent: false,
        socket: Socket {
            connecting: false,
            _hadError: false,
            _handle: [TCP],
            _parent: null,
            _host: null,
            _readableState: [ReadableState],
            readable: true,
            _events: [Object],
            _eventsCount: 9,
            _maxListeners: undefined,
            _writableState: [WritableState],
            writable: true,
            _bytesDispatched: 0,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            allowHalfOpen: true,
            server: [Server],
            _server: [Server],
            _idleTimeout: 120000,
            _idleNext: [TimersList],
            _idlePrev: [TimersList],
            _idleStart: 599,
            _destroyed: false,
            parser: [HTTPParser],
            on: [Function: socketOnWrap],
            _paused: false,
            _httpMessage: [Circular],
            _peername: [Object],
            [Symbol(asyncId)]: 8,
            [Symbol(lastWriteQueueSize)]: 0,
            [Symbol(bytesRead)]: 0,
            [Symbol(asyncId)]: 10,
            [Symbol(triggerAsyncId)]: 8
        },
        connection: Socket {
            connecting: false,
            _hadError: false,
            _handle: [TCP],
            _parent: null,
            _host: null,
            _readableState: [ReadableState],
            readable: true,
            _events: [Object],
            _eventsCount: 9,
            _maxListeners: undefined,
            _writableState: [WritableState],
            writable: true,
            _bytesDispatched: 0,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            allowHalfOpen: true,
            server: [Server],
            _server: [Server],
            _idleTimeout: 120000,
            _idleNext: [TimersList],
            _idlePrev: [TimersList],
            _idleStart: 599,
            _destroyed: false,
            parser: [HTTPParser],
            on: [Function: socketOnWrap],
            _paused: false,
            _httpMessage: [Circular],
            _peername: [Object],
            [Symbol(asyncId)]: 8,
            [Symbol(lastWriteQueueSize)]: 0,
            [Symbol(bytesRead)]: 0,
            [Symbol(asyncId)]: 10,
            [Symbol(triggerAsyncId)]: 8
        },
        _header: null,
        _onPendingData: [Function: bound updateOutgoingData],
        _sent100: false,
        _expect_continue: false,
        req: [Circular],
        locals: {},
        _startAt: undefined,
        _startTime: undefined,
        writeHead: [Function: writeHead],
        __onFinished: {
            [Function: listener] queue: [Array]
        },
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: {
            'x-powered-by': [Array]
        }
    },
    _startAt: [145474, 930317687],
    _startTime: 2018 - 05 - 05 T09: 23: 54.988 Z,
    _remoteAddress: '::1',
    body: {},
    secret: undefined,
    cookies: {},
    signedCookies: {},
    _parsedOriginalUrl: Url {
        protocol: null,
        slashes: null,
        auth: null,
        host: null,
        port: null,
        hostname: null,
        hash: null,
        search: '?url=https%3a%2f%2fgetsharex.com',
        query: 'url=https%3a%2f%2fgetsharex.com',
        pathname: '/api/v1/shortener',
        path: '/api/v1/shortener?url=https%3a%2f%2fgetsharex.com',
        href: '/api/v1/shortener?url=https%3a%2f%2fgetsharex.com',
        _raw: '/api/v1/shortener?url=https%3a%2f%2fgetsharex.com'
    },
    route: Route {
        path: '/api/v1/shortener',
        stack: [
            [Layer]
        ],
        methods: {
            get: true
        }
    }
}